### PR TITLE
Feature/new course page design

### PR DESCRIPTION
**Pull request by eg270-unikent**

### CODE REVIEW

**Comment by eg270-unikent** [comment]
@aw285-unikent I've put this back to do not merge, as it needs some discussion about how EMS will manage the images etc. It will require some of your time to get it looking exactly how you want so we could deploy this branch to test for you to have a play around with and ensure you're happy with the changes.

**Comment by aw285-unikent** [comment]
@aw285-unikent - if you could deploy it to test that would be great, then perhaps I can have a look at it and come over later today/in the week to discuss any changes and managing the images etc?

**Comment by aw285-unikent** [comment]
@eg270-unikent tagged above

**Comment by eg270-unikent** [comment]
@aw285-unikent please can you update us on this once you have had the meeting re: student experience page?

**Comment by eg270-unikent** [comment]
This can now be merged as Angela is happy for this to go live.

**Pull request merged**
